server:
  port: 9090
  servlet:
    # 应用的访问路径
    context-path: /

logging:
  level:
    root: debug
# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: druid, redis, cache
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

# MyBatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml

security:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
    password:
      maxRetryCount: 5
      # 密码错误{maxRetryCount}次锁定多少秒
      lockTime: 600
  cookie:
    name: SESSION
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
    # 只在https部署下允许开启
    secure: false
    # 可选值 Strict Lax None (None只有同时设置secure属性时生效)
    sameSite: Lax
    # cookie的值是否使用base64编码
    useBase64: true
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: 1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickOutAfter: false
    # session存储方式，none表示通过map存储，redis表示通过redis存储
    store-type: redis
  rememberMe:
    # 是否开启记住我
    enabled: true

ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 5.0.0
  # 版权年份
  copyrightYear: 2022
  # 实例演示开关
  demoEnabled: true
  # 获取ip地址开关
  addressEnabled: false
  # 异步任务线程池配置
  threadpool:
    # 核心线程数大小
    corePoolSize: 10
    # 最大线程数
    maxPoolSize: 10
    # 队列容量
    queueCapacity: 20
    # 活跃时间
    keepAliveSeconds: 10